//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinisterioDeportes.ReferenceMinisterioDeportesWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="deporte", Namespace="http://schemas.datacontract.org/2004/07/MinisterioDeportesAccesoADatos")]
    [System.SerializableAttribute()]
    public partial class deporte : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MinisterioDeportes.ReferenceMinisterioDeportesWCF.persona[] personaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MinisterioDeportes.ReferenceMinisterioDeportesWCF.plan[] planField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MinisterioDeportes.ReferenceMinisterioDeportesWCF.persona[] persona {
            get {
                return this.personaField;
            }
            set {
                if ((object.ReferenceEquals(this.personaField, value) != true)) {
                    this.personaField = value;
                    this.RaisePropertyChanged("persona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MinisterioDeportes.ReferenceMinisterioDeportesWCF.plan[] plan {
            get {
                return this.planField;
            }
            set {
                if ((object.ReferenceEquals(this.planField, value) != true)) {
                    this.planField = value;
                    this.RaisePropertyChanged("plan");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="persona", Namespace="http://schemas.datacontract.org/2004/07/MinisterioDeportesAccesoADatos")]
    [System.SerializableAttribute()]
    public partial class persona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellido2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MinisterioDeportes.ReferenceMinisterioDeportesWCF.deporte[] deporteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool is_adminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellido {
            get {
                return this.apellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidoField, value) != true)) {
                    this.apellidoField = value;
                    this.RaisePropertyChanged("apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellido2 {
            get {
                return this.apellido2Field;
            }
            set {
                if ((object.ReferenceEquals(this.apellido2Field, value) != true)) {
                    this.apellido2Field = value;
                    this.RaisePropertyChanged("apellido2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cedula {
            get {
                return this.cedulaField;
            }
            set {
                if ((this.cedulaField.Equals(value) != true)) {
                    this.cedulaField = value;
                    this.RaisePropertyChanged("cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MinisterioDeportes.ReferenceMinisterioDeportesWCF.deporte[] deporte {
            get {
                return this.deporteField;
            }
            set {
                if ((object.ReferenceEquals(this.deporteField, value) != true)) {
                    this.deporteField = value;
                    this.RaisePropertyChanged("deporte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool is_admin {
            get {
                return this.is_adminField;
            }
            set {
                if ((this.is_adminField.Equals(value) != true)) {
                    this.is_adminField = value;
                    this.RaisePropertyChanged("is_admin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="plan", Namespace="http://schemas.datacontract.org/2004/07/MinisterioDeportesAccesoADatos")]
    [System.SerializableAttribute()]
    public partial class plan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MinisterioDeportes.ReferenceMinisterioDeportesWCF.deporte[] deporteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string detallesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MinisterioDeportes.ReferenceMinisterioDeportesWCF.rutina[] rutinaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MinisterioDeportes.ReferenceMinisterioDeportesWCF.deporte[] deporte {
            get {
                return this.deporteField;
            }
            set {
                if ((object.ReferenceEquals(this.deporteField, value) != true)) {
                    this.deporteField = value;
                    this.RaisePropertyChanged("deporte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string detalles {
            get {
                return this.detallesField;
            }
            set {
                if ((object.ReferenceEquals(this.detallesField, value) != true)) {
                    this.detallesField = value;
                    this.RaisePropertyChanged("detalles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MinisterioDeportes.ReferenceMinisterioDeportesWCF.rutina[] rutina {
            get {
                return this.rutinaField;
            }
            set {
                if ((object.ReferenceEquals(this.rutinaField, value) != true)) {
                    this.rutinaField = value;
                    this.RaisePropertyChanged("rutina");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="rutina", Namespace="http://schemas.datacontract.org/2004/07/MinisterioDeportesAccesoADatos")]
    [System.SerializableAttribute()]
    public partial class rutina : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MinisterioDeportes.ReferenceMinisterioDeportesWCF.plan[] planField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MinisterioDeportes.ReferenceMinisterioDeportesWCF.plan[] plan {
            get {
                return this.planField;
            }
            set {
                if ((object.ReferenceEquals(this.planField, value) != true)) {
                    this.planField = value;
                    this.RaisePropertyChanged("plan");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReferenceMinisterioDeportesWCF.IWebServiceMD")]
    public interface IWebServiceMD {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/AgregarDeporte", ReplyAction="http://tempuri.org/IWebServiceMD/AgregarDeporteResponse")]
        string AgregarDeporte(MinisterioDeportes.ReferenceMinisterioDeportesWCF.deporte deporte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/AgregarDeporte", ReplyAction="http://tempuri.org/IWebServiceMD/AgregarDeporteResponse")]
        System.Threading.Tasks.Task<string> AgregarDeporteAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.deporte deporte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/EliminarDeporte", ReplyAction="http://tempuri.org/IWebServiceMD/EliminarDeporteResponse")]
        string EliminarDeporte(MinisterioDeportes.ReferenceMinisterioDeportesWCF.deporte deporte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/EliminarDeporte", ReplyAction="http://tempuri.org/IWebServiceMD/EliminarDeporteResponse")]
        System.Threading.Tasks.Task<string> EliminarDeporteAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.deporte deporte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/EditarDeporte", ReplyAction="http://tempuri.org/IWebServiceMD/EditarDeporteResponse")]
        string EditarDeporte(MinisterioDeportes.ReferenceMinisterioDeportesWCF.deporte deporte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/EditarDeporte", ReplyAction="http://tempuri.org/IWebServiceMD/EditarDeporteResponse")]
        System.Threading.Tasks.Task<string> EditarDeporteAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.deporte deporte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/ObtenerDeporte", ReplyAction="http://tempuri.org/IWebServiceMD/ObtenerDeporteResponse")]
        MinisterioDeportes.ReferenceMinisterioDeportesWCF.deporte[] ObtenerDeporte(string filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/ObtenerDeporte", ReplyAction="http://tempuri.org/IWebServiceMD/ObtenerDeporteResponse")]
        System.Threading.Tasks.Task<MinisterioDeportes.ReferenceMinisterioDeportesWCF.deporte[]> ObtenerDeporteAsync(string filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/ValidarUsuario", ReplyAction="http://tempuri.org/IWebServiceMD/ValidarUsuarioResponse")]
        MinisterioDeportes.ReferenceMinisterioDeportesWCF.persona ValidarUsuario(MinisterioDeportes.ReferenceMinisterioDeportesWCF.persona usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/ValidarUsuario", ReplyAction="http://tempuri.org/IWebServiceMD/ValidarUsuarioResponse")]
        System.Threading.Tasks.Task<MinisterioDeportes.ReferenceMinisterioDeportesWCF.persona> ValidarUsuarioAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.persona usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/AgregarPersona", ReplyAction="http://tempuri.org/IWebServiceMD/AgregarPersonaResponse")]
        string AgregarPersona(MinisterioDeportes.ReferenceMinisterioDeportesWCF.persona persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/AgregarPersona", ReplyAction="http://tempuri.org/IWebServiceMD/AgregarPersonaResponse")]
        System.Threading.Tasks.Task<string> AgregarPersonaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.persona persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/EliminarPersona", ReplyAction="http://tempuri.org/IWebServiceMD/EliminarPersonaResponse")]
        void EliminarPersona(MinisterioDeportes.ReferenceMinisterioDeportesWCF.persona persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/EliminarPersona", ReplyAction="http://tempuri.org/IWebServiceMD/EliminarPersonaResponse")]
        System.Threading.Tasks.Task EliminarPersonaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.persona persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/EditarPersona", ReplyAction="http://tempuri.org/IWebServiceMD/EditarPersonaResponse")]
        void EditarPersona(MinisterioDeportes.ReferenceMinisterioDeportesWCF.persona persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/EditarPersona", ReplyAction="http://tempuri.org/IWebServiceMD/EditarPersonaResponse")]
        System.Threading.Tasks.Task EditarPersonaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.persona persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/ObtenerPersona", ReplyAction="http://tempuri.org/IWebServiceMD/ObtenerPersonaResponse")]
        void ObtenerPersona();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/ObtenerPersona", ReplyAction="http://tempuri.org/IWebServiceMD/ObtenerPersonaResponse")]
        System.Threading.Tasks.Task ObtenerPersonaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/AgregarRutina", ReplyAction="http://tempuri.org/IWebServiceMD/AgregarRutinaResponse")]
        bool AgregarRutina(MinisterioDeportes.ReferenceMinisterioDeportesWCF.rutina rutina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/AgregarRutina", ReplyAction="http://tempuri.org/IWebServiceMD/AgregarRutinaResponse")]
        System.Threading.Tasks.Task<bool> AgregarRutinaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.rutina rutina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/EliminarRutina", ReplyAction="http://tempuri.org/IWebServiceMD/EliminarRutinaResponse")]
        void EliminarRutina(MinisterioDeportes.ReferenceMinisterioDeportesWCF.rutina rutina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/EliminarRutina", ReplyAction="http://tempuri.org/IWebServiceMD/EliminarRutinaResponse")]
        System.Threading.Tasks.Task EliminarRutinaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.rutina rutina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/EditarRutina", ReplyAction="http://tempuri.org/IWebServiceMD/EditarRutinaResponse")]
        void EditarRutina(MinisterioDeportes.ReferenceMinisterioDeportesWCF.rutina rutina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/EditarRutina", ReplyAction="http://tempuri.org/IWebServiceMD/EditarRutinaResponse")]
        System.Threading.Tasks.Task EditarRutinaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.rutina rutina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/ObtenerRutina", ReplyAction="http://tempuri.org/IWebServiceMD/ObtenerRutinaResponse")]
        void ObtenerRutina();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/ObtenerRutina", ReplyAction="http://tempuri.org/IWebServiceMD/ObtenerRutinaResponse")]
        System.Threading.Tasks.Task ObtenerRutinaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/AgregarPlanRutina", ReplyAction="http://tempuri.org/IWebServiceMD/AgregarPlanRutinaResponse")]
        bool AgregarPlanRutina(MinisterioDeportes.ReferenceMinisterioDeportesWCF.plan planRutina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/AgregarPlanRutina", ReplyAction="http://tempuri.org/IWebServiceMD/AgregarPlanRutinaResponse")]
        System.Threading.Tasks.Task<bool> AgregarPlanRutinaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.plan planRutina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/EliminarPlanRutina", ReplyAction="http://tempuri.org/IWebServiceMD/EliminarPlanRutinaResponse")]
        void EliminarPlanRutina(MinisterioDeportes.ReferenceMinisterioDeportesWCF.plan planRutina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/EliminarPlanRutina", ReplyAction="http://tempuri.org/IWebServiceMD/EliminarPlanRutinaResponse")]
        System.Threading.Tasks.Task EliminarPlanRutinaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.plan planRutina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/EditarPlanRutina", ReplyAction="http://tempuri.org/IWebServiceMD/EditarPlanRutinaResponse")]
        void EditarPlanRutina(MinisterioDeportes.ReferenceMinisterioDeportesWCF.plan planRutina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/EditarPlanRutina", ReplyAction="http://tempuri.org/IWebServiceMD/EditarPlanRutinaResponse")]
        System.Threading.Tasks.Task EditarPlanRutinaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.plan planRutina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/ObtenerPlanRutina", ReplyAction="http://tempuri.org/IWebServiceMD/ObtenerPlanRutinaResponse")]
        void ObtenerPlanRutina();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/ObtenerPlanRutina", ReplyAction="http://tempuri.org/IWebServiceMD/ObtenerPlanRutinaResponse")]
        System.Threading.Tasks.Task ObtenerPlanRutinaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebServiceMDChannel : MinisterioDeportes.ReferenceMinisterioDeportesWCF.IWebServiceMD, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceMDClient : System.ServiceModel.ClientBase<MinisterioDeportes.ReferenceMinisterioDeportesWCF.IWebServiceMD>, MinisterioDeportes.ReferenceMinisterioDeportesWCF.IWebServiceMD {
        
        public WebServiceMDClient() {
        }
        
        public WebServiceMDClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceMDClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMDClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMDClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AgregarDeporte(MinisterioDeportes.ReferenceMinisterioDeportesWCF.deporte deporte) {
            return base.Channel.AgregarDeporte(deporte);
        }
        
        public System.Threading.Tasks.Task<string> AgregarDeporteAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.deporte deporte) {
            return base.Channel.AgregarDeporteAsync(deporte);
        }
        
        public string EliminarDeporte(MinisterioDeportes.ReferenceMinisterioDeportesWCF.deporte deporte) {
            return base.Channel.EliminarDeporte(deporte);
        }
        
        public System.Threading.Tasks.Task<string> EliminarDeporteAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.deporte deporte) {
            return base.Channel.EliminarDeporteAsync(deporte);
        }
        
        public string EditarDeporte(MinisterioDeportes.ReferenceMinisterioDeportesWCF.deporte deporte) {
            return base.Channel.EditarDeporte(deporte);
        }
        
        public System.Threading.Tasks.Task<string> EditarDeporteAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.deporte deporte) {
            return base.Channel.EditarDeporteAsync(deporte);
        }
        
        public MinisterioDeportes.ReferenceMinisterioDeportesWCF.deporte[] ObtenerDeporte(string filtro) {
            return base.Channel.ObtenerDeporte(filtro);
        }
        
        public System.Threading.Tasks.Task<MinisterioDeportes.ReferenceMinisterioDeportesWCF.deporte[]> ObtenerDeporteAsync(string filtro) {
            return base.Channel.ObtenerDeporteAsync(filtro);
        }
        
        public MinisterioDeportes.ReferenceMinisterioDeportesWCF.persona ValidarUsuario(MinisterioDeportes.ReferenceMinisterioDeportesWCF.persona usuario) {
            return base.Channel.ValidarUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<MinisterioDeportes.ReferenceMinisterioDeportesWCF.persona> ValidarUsuarioAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.persona usuario) {
            return base.Channel.ValidarUsuarioAsync(usuario);
        }
        
        public string AgregarPersona(MinisterioDeportes.ReferenceMinisterioDeportesWCF.persona persona) {
            return base.Channel.AgregarPersona(persona);
        }
        
        public System.Threading.Tasks.Task<string> AgregarPersonaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.persona persona) {
            return base.Channel.AgregarPersonaAsync(persona);
        }
        
        public void EliminarPersona(MinisterioDeportes.ReferenceMinisterioDeportesWCF.persona persona) {
            base.Channel.EliminarPersona(persona);
        }
        
        public System.Threading.Tasks.Task EliminarPersonaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.persona persona) {
            return base.Channel.EliminarPersonaAsync(persona);
        }
        
        public void EditarPersona(MinisterioDeportes.ReferenceMinisterioDeportesWCF.persona persona) {
            base.Channel.EditarPersona(persona);
        }
        
        public System.Threading.Tasks.Task EditarPersonaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.persona persona) {
            return base.Channel.EditarPersonaAsync(persona);
        }
        
        public void ObtenerPersona() {
            base.Channel.ObtenerPersona();
        }
        
        public System.Threading.Tasks.Task ObtenerPersonaAsync() {
            return base.Channel.ObtenerPersonaAsync();
        }
        
        public bool AgregarRutina(MinisterioDeportes.ReferenceMinisterioDeportesWCF.rutina rutina) {
            return base.Channel.AgregarRutina(rutina);
        }
        
        public System.Threading.Tasks.Task<bool> AgregarRutinaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.rutina rutina) {
            return base.Channel.AgregarRutinaAsync(rutina);
        }
        
        public void EliminarRutina(MinisterioDeportes.ReferenceMinisterioDeportesWCF.rutina rutina) {
            base.Channel.EliminarRutina(rutina);
        }
        
        public System.Threading.Tasks.Task EliminarRutinaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.rutina rutina) {
            return base.Channel.EliminarRutinaAsync(rutina);
        }
        
        public void EditarRutina(MinisterioDeportes.ReferenceMinisterioDeportesWCF.rutina rutina) {
            base.Channel.EditarRutina(rutina);
        }
        
        public System.Threading.Tasks.Task EditarRutinaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.rutina rutina) {
            return base.Channel.EditarRutinaAsync(rutina);
        }
        
        public void ObtenerRutina() {
            base.Channel.ObtenerRutina();
        }
        
        public System.Threading.Tasks.Task ObtenerRutinaAsync() {
            return base.Channel.ObtenerRutinaAsync();
        }
        
        public bool AgregarPlanRutina(MinisterioDeportes.ReferenceMinisterioDeportesWCF.plan planRutina) {
            return base.Channel.AgregarPlanRutina(planRutina);
        }
        
        public System.Threading.Tasks.Task<bool> AgregarPlanRutinaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.plan planRutina) {
            return base.Channel.AgregarPlanRutinaAsync(planRutina);
        }
        
        public void EliminarPlanRutina(MinisterioDeportes.ReferenceMinisterioDeportesWCF.plan planRutina) {
            base.Channel.EliminarPlanRutina(planRutina);
        }
        
        public System.Threading.Tasks.Task EliminarPlanRutinaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.plan planRutina) {
            return base.Channel.EliminarPlanRutinaAsync(planRutina);
        }
        
        public void EditarPlanRutina(MinisterioDeportes.ReferenceMinisterioDeportesWCF.plan planRutina) {
            base.Channel.EditarPlanRutina(planRutina);
        }
        
        public System.Threading.Tasks.Task EditarPlanRutinaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.plan planRutina) {
            return base.Channel.EditarPlanRutinaAsync(planRutina);
        }
        
        public void ObtenerPlanRutina() {
            base.Channel.ObtenerPlanRutina();
        }
        
        public System.Threading.Tasks.Task ObtenerPlanRutinaAsync() {
            return base.Channel.ObtenerPlanRutinaAsync();
        }
    }
}
