//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinisterioDeportes.ReferenceMinisterioDeportesWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonaDTO", Namespace="http://schemas.datacontract.org/2004/07/MinisterioDeportesWCF.Entidades")]
    [System.SerializableAttribute()]
    public partial class PersonaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellido1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellido2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string correoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool esAdmiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellido1 {
            get {
                return this.apellido1Field;
            }
            set {
                if ((object.ReferenceEquals(this.apellido1Field, value) != true)) {
                    this.apellido1Field = value;
                    this.RaisePropertyChanged("apellido1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellido2 {
            get {
                return this.apellido2Field;
            }
            set {
                if ((object.ReferenceEquals(this.apellido2Field, value) != true)) {
                    this.apellido2Field = value;
                    this.RaisePropertyChanged("apellido2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cedula {
            get {
                return this.cedulaField;
            }
            set {
                if ((this.cedulaField.Equals(value) != true)) {
                    this.cedulaField = value;
                    this.RaisePropertyChanged("cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                if ((object.ReferenceEquals(this.correoField, value) != true)) {
                    this.correoField = value;
                    this.RaisePropertyChanged("correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool esAdmi {
            get {
                return this.esAdmiField;
            }
            set {
                if ((this.esAdmiField.Equals(value) != true)) {
                    this.esAdmiField = value;
                    this.RaisePropertyChanged("esAdmi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeporteDTO", Namespace="http://schemas.datacontract.org/2004/07/MinisterioDeportesWCF.Entidades")]
    [System.SerializableAttribute()]
    public partial class DeporteDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short IdField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;        
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                if ((this.IdField.Equals(value) != true))
                {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }               
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="persona", Namespace="http://schemas.datacontract.org/2004/07/MinisterioDeportesAccesoADatos")]
    [System.SerializableAttribute()]
    public partial class persona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellido2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MinisterioDeportes.ReferenceMinisterioDeportesWCF.deporte[] deporteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool is_adminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellido {
            get {
                return this.apellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidoField, value) != true)) {
                    this.apellidoField = value;
                    this.RaisePropertyChanged("apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellido2 {
            get {
                return this.apellido2Field;
            }
            set {
                if ((object.ReferenceEquals(this.apellido2Field, value) != true)) {
                    this.apellido2Field = value;
                    this.RaisePropertyChanged("apellido2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cedula {
            get {
                return this.cedulaField;
            }
            set {
                if ((this.cedulaField.Equals(value) != true)) {
                    this.cedulaField = value;
                    this.RaisePropertyChanged("cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MinisterioDeportes.ReferenceMinisterioDeportesWCF.deporte[] deporte {
            get {
                return this.deporteField;
            }
            set {
                if ((object.ReferenceEquals(this.deporteField, value) != true)) {
                    this.deporteField = value;
                    this.RaisePropertyChanged("deporte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool is_admin {
            get {
                return this.is_adminField;
            }
            set {
                if ((this.is_adminField.Equals(value) != true)) {
                    this.is_adminField = value;
                    this.RaisePropertyChanged("is_admin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="deporte", Namespace="http://schemas.datacontract.org/2004/07/MinisterioDeportesAccesoADatos")]
    [System.SerializableAttribute()]
    public partial class deporte : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MinisterioDeportes.ReferenceMinisterioDeportesWCF.persona[] personaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MinisterioDeportes.ReferenceMinisterioDeportesWCF.plan[] planField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MinisterioDeportes.ReferenceMinisterioDeportesWCF.persona[] persona {
            get {
                return this.personaField;
            }
            set {
                if ((object.ReferenceEquals(this.personaField, value) != true)) {
                    this.personaField = value;
                    this.RaisePropertyChanged("persona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MinisterioDeportes.ReferenceMinisterioDeportesWCF.plan[] plan {
            get {
                return this.planField;
            }
            set {
                if ((object.ReferenceEquals(this.planField, value) != true)) {
                    this.planField = value;
                    this.RaisePropertyChanged("plan");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="plan", Namespace="http://schemas.datacontract.org/2004/07/MinisterioDeportesAccesoADatos")]
    [System.SerializableAttribute()]
    public partial class plan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MinisterioDeportes.ReferenceMinisterioDeportesWCF.deporte[] deporteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string detallesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MinisterioDeportes.ReferenceMinisterioDeportesWCF.rutina[] rutinaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MinisterioDeportes.ReferenceMinisterioDeportesWCF.deporte[] deporte {
            get {
                return this.deporteField;
            }
            set {
                if ((object.ReferenceEquals(this.deporteField, value) != true)) {
                    this.deporteField = value;
                    this.RaisePropertyChanged("deporte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string detalles {
            get {
                return this.detallesField;
            }
            set {
                if ((object.ReferenceEquals(this.detallesField, value) != true)) {
                    this.detallesField = value;
                    this.RaisePropertyChanged("detalles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MinisterioDeportes.ReferenceMinisterioDeportesWCF.rutina[] rutina {
            get {
                return this.rutinaField;
            }
            set {
                if ((object.ReferenceEquals(this.rutinaField, value) != true)) {
                    this.rutinaField = value;
                    this.RaisePropertyChanged("rutina");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="rutina", Namespace="http://schemas.datacontract.org/2004/07/MinisterioDeportesAccesoADatos")]
    [System.SerializableAttribute()]
    public partial class rutina : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MinisterioDeportes.ReferenceMinisterioDeportesWCF.plan[] planField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MinisterioDeportes.ReferenceMinisterioDeportesWCF.plan[] plan {
            get {
                return this.planField;
            }
            set {
                if ((object.ReferenceEquals(this.planField, value) != true)) {
                    this.planField = value;
                    this.RaisePropertyChanged("plan");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReferenceMinisterioDeportesWCF.IWebServiceMD")]
    public interface IWebServiceMD {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/ValidarLogin", ReplyAction="http://tempuri.org/IWebServiceMD/ValidarLoginResponse")]
        MinisterioDeportes.ReferenceMinisterioDeportesWCF.PersonaDTO ValidarLogin(MinisterioDeportes.ReferenceMinisterioDeportesWCF.PersonaDTO usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/ValidarLogin", ReplyAction="http://tempuri.org/IWebServiceMD/ValidarLoginResponse")]
        System.Threading.Tasks.Task<MinisterioDeportes.ReferenceMinisterioDeportesWCF.PersonaDTO> ValidarLoginAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.PersonaDTO usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/AgregarDeporte", ReplyAction="http://tempuri.org/IWebServiceMD/AgregarDeporteResponse")]
        string AgregarDeporte(MinisterioDeportes.ReferenceMinisterioDeportesWCF.DeporteDTO deporte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/AgregarDeporte", ReplyAction="http://tempuri.org/IWebServiceMD/AgregarDeporteResponse")]
        System.Threading.Tasks.Task<string> AgregarDeporteAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.DeporteDTO deporte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/EliminarDeporte", ReplyAction="http://tempuri.org/IWebServiceMD/EliminarDeporteResponse")]
        string EliminarDeporte(MinisterioDeportes.ReferenceMinisterioDeportesWCF.DeporteDTO deporte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/EliminarDeporte", ReplyAction="http://tempuri.org/IWebServiceMD/EliminarDeporteResponse")]
        System.Threading.Tasks.Task<string> EliminarDeporteAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.DeporteDTO deporte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/EditarDeporte", ReplyAction="http://tempuri.org/IWebServiceMD/EditarDeporteResponse")]
        string EditarDeporte(MinisterioDeportes.ReferenceMinisterioDeportesWCF.DeporteDTO deporte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/EditarDeporte", ReplyAction="http://tempuri.org/IWebServiceMD/EditarDeporteResponse")]
        System.Threading.Tasks.Task<string> EditarDeporteAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.DeporteDTO deporte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/ObtenerDeportes", ReplyAction="http://tempuri.org/IWebServiceMD/ObtenerDeportesResponse")]
        MinisterioDeportes.ReferenceMinisterioDeportesWCF.DeporteDTO[] ObtenerDeportes(string filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/ObtenerDeportes", ReplyAction="http://tempuri.org/IWebServiceMD/ObtenerDeportesResponse")]
        System.Threading.Tasks.Task<MinisterioDeportes.ReferenceMinisterioDeportesWCF.DeporteDTO[]> ObtenerDeportesAsync(string filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/AgregarPersona", ReplyAction="http://tempuri.org/IWebServiceMD/AgregarPersonaResponse")]
        string AgregarPersona(MinisterioDeportes.ReferenceMinisterioDeportesWCF.persona persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/AgregarPersona", ReplyAction="http://tempuri.org/IWebServiceMD/AgregarPersonaResponse")]
        System.Threading.Tasks.Task<string> AgregarPersonaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.persona persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/EliminarPersona", ReplyAction="http://tempuri.org/IWebServiceMD/EliminarPersonaResponse")]
        string EliminarPersona(MinisterioDeportes.ReferenceMinisterioDeportesWCF.persona persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/EliminarPersona", ReplyAction="http://tempuri.org/IWebServiceMD/EliminarPersonaResponse")]
        System.Threading.Tasks.Task<string> EliminarPersonaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.persona persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/EditarPersona", ReplyAction="http://tempuri.org/IWebServiceMD/EditarPersonaResponse")]
        string EditarPersona(MinisterioDeportes.ReferenceMinisterioDeportesWCF.persona persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/EditarPersona", ReplyAction="http://tempuri.org/IWebServiceMD/EditarPersonaResponse")]
        System.Threading.Tasks.Task<string> EditarPersonaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.persona persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/ObtenerPersona", ReplyAction="http://tempuri.org/IWebServiceMD/ObtenerPersonaResponse")]
        MinisterioDeportes.ReferenceMinisterioDeportesWCF.persona[] ObtenerPersona(string filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/ObtenerPersona", ReplyAction="http://tempuri.org/IWebServiceMD/ObtenerPersonaResponse")]
        System.Threading.Tasks.Task<MinisterioDeportes.ReferenceMinisterioDeportesWCF.persona[]> ObtenerPersonaAsync(string filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/AgregarRutina", ReplyAction="http://tempuri.org/IWebServiceMD/AgregarRutinaResponse")]
        string AgregarRutina(MinisterioDeportes.ReferenceMinisterioDeportesWCF.rutina rutina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/AgregarRutina", ReplyAction="http://tempuri.org/IWebServiceMD/AgregarRutinaResponse")]
        System.Threading.Tasks.Task<string> AgregarRutinaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.rutina rutina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/EliminarRutina", ReplyAction="http://tempuri.org/IWebServiceMD/EliminarRutinaResponse")]
        string EliminarRutina(MinisterioDeportes.ReferenceMinisterioDeportesWCF.rutina rutina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/EliminarRutina", ReplyAction="http://tempuri.org/IWebServiceMD/EliminarRutinaResponse")]
        System.Threading.Tasks.Task<string> EliminarRutinaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.rutina rutina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/EditarRutina", ReplyAction="http://tempuri.org/IWebServiceMD/EditarRutinaResponse")]
        string EditarRutina(MinisterioDeportes.ReferenceMinisterioDeportesWCF.rutina rutina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/EditarRutina", ReplyAction="http://tempuri.org/IWebServiceMD/EditarRutinaResponse")]
        System.Threading.Tasks.Task<string> EditarRutinaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.rutina rutina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/ObtenerRutina", ReplyAction="http://tempuri.org/IWebServiceMD/ObtenerRutinaResponse")]
        MinisterioDeportes.ReferenceMinisterioDeportesWCF.rutina[] ObtenerRutina(string filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/ObtenerRutina", ReplyAction="http://tempuri.org/IWebServiceMD/ObtenerRutinaResponse")]
        System.Threading.Tasks.Task<MinisterioDeportes.ReferenceMinisterioDeportesWCF.rutina[]> ObtenerRutinaAsync(string filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/AgregarPlanRutina", ReplyAction="http://tempuri.org/IWebServiceMD/AgregarPlanRutinaResponse")]
        string AgregarPlanRutina(MinisterioDeportes.ReferenceMinisterioDeportesWCF.plan planRutina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/AgregarPlanRutina", ReplyAction="http://tempuri.org/IWebServiceMD/AgregarPlanRutinaResponse")]
        System.Threading.Tasks.Task<string> AgregarPlanRutinaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.plan planRutina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/EliminarPlanRutina", ReplyAction="http://tempuri.org/IWebServiceMD/EliminarPlanRutinaResponse")]
        string EliminarPlanRutina(MinisterioDeportes.ReferenceMinisterioDeportesWCF.plan planRutina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/EliminarPlanRutina", ReplyAction="http://tempuri.org/IWebServiceMD/EliminarPlanRutinaResponse")]
        System.Threading.Tasks.Task<string> EliminarPlanRutinaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.plan planRutina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/EditarPlanRutina", ReplyAction="http://tempuri.org/IWebServiceMD/EditarPlanRutinaResponse")]
        string EditarPlanRutina(MinisterioDeportes.ReferenceMinisterioDeportesWCF.plan planRutina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/EditarPlanRutina", ReplyAction="http://tempuri.org/IWebServiceMD/EditarPlanRutinaResponse")]
        System.Threading.Tasks.Task<string> EditarPlanRutinaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.plan planRutina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/ObtenerPlanRutina", ReplyAction="http://tempuri.org/IWebServiceMD/ObtenerPlanRutinaResponse")]
        MinisterioDeportes.ReferenceMinisterioDeportesWCF.plan[] ObtenerPlanRutina(string filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/ObtenerPlanRutina", ReplyAction="http://tempuri.org/IWebServiceMD/ObtenerPlanRutinaResponse")]
        System.Threading.Tasks.Task<MinisterioDeportes.ReferenceMinisterioDeportesWCF.plan[]> ObtenerPlanRutinaAsync(string filtro);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebServiceMDChannel : MinisterioDeportes.ReferenceMinisterioDeportesWCF.IWebServiceMD, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceMDClient : System.ServiceModel.ClientBase<MinisterioDeportes.ReferenceMinisterioDeportesWCF.IWebServiceMD>, MinisterioDeportes.ReferenceMinisterioDeportesWCF.IWebServiceMD {
        
        public WebServiceMDClient() {
        }
        
        public WebServiceMDClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceMDClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMDClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMDClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MinisterioDeportes.ReferenceMinisterioDeportesWCF.PersonaDTO ValidarLogin(MinisterioDeportes.ReferenceMinisterioDeportesWCF.PersonaDTO usuario) {
            return base.Channel.ValidarLogin(usuario);
        }
        
        public System.Threading.Tasks.Task<MinisterioDeportes.ReferenceMinisterioDeportesWCF.PersonaDTO> ValidarLoginAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.PersonaDTO usuario) {
            return base.Channel.ValidarLoginAsync(usuario);
        }
        
        public string AgregarDeporte(MinisterioDeportes.ReferenceMinisterioDeportesWCF.DeporteDTO deporte) {
            return base.Channel.AgregarDeporte(deporte);
        }
        
        public System.Threading.Tasks.Task<string> AgregarDeporteAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.DeporteDTO deporte) {
            return base.Channel.AgregarDeporteAsync(deporte);
        }
        
        public string EliminarDeporte(MinisterioDeportes.ReferenceMinisterioDeportesWCF.DeporteDTO deporte) {
            return base.Channel.EliminarDeporte(deporte);
        }
        
        public System.Threading.Tasks.Task<string> EliminarDeporteAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.DeporteDTO deporte) {
            return base.Channel.EliminarDeporteAsync(deporte);
        }
        
        public string EditarDeporte(MinisterioDeportes.ReferenceMinisterioDeportesWCF.DeporteDTO deporte) {
            return base.Channel.EditarDeporte(deporte);
        }
        
        public System.Threading.Tasks.Task<string> EditarDeporteAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.DeporteDTO deporte) {
            return base.Channel.EditarDeporteAsync(deporte);
        }
        
        public MinisterioDeportes.ReferenceMinisterioDeportesWCF.DeporteDTO[] ObtenerDeportes(string filtro) {
            return base.Channel.ObtenerDeportes(filtro);
        }
        
        public System.Threading.Tasks.Task<MinisterioDeportes.ReferenceMinisterioDeportesWCF.DeporteDTO[]> ObtenerDeportesAsync(string filtro) {
            return base.Channel.ObtenerDeportesAsync(filtro);
        }
        
        public string AgregarPersona(MinisterioDeportes.ReferenceMinisterioDeportesWCF.persona persona) {
            return base.Channel.AgregarPersona(persona);
        }
        
        public System.Threading.Tasks.Task<string> AgregarPersonaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.persona persona) {
            return base.Channel.AgregarPersonaAsync(persona);
        }
        
        public string EliminarPersona(MinisterioDeportes.ReferenceMinisterioDeportesWCF.persona persona) {
            return base.Channel.EliminarPersona(persona);
        }
        
        public System.Threading.Tasks.Task<string> EliminarPersonaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.persona persona) {
            return base.Channel.EliminarPersonaAsync(persona);
        }
        
        public string EditarPersona(MinisterioDeportes.ReferenceMinisterioDeportesWCF.persona persona) {
            return base.Channel.EditarPersona(persona);
        }
        
        public System.Threading.Tasks.Task<string> EditarPersonaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.persona persona) {
            return base.Channel.EditarPersonaAsync(persona);
        }
        
        public MinisterioDeportes.ReferenceMinisterioDeportesWCF.persona[] ObtenerPersona(string filtro) {
            return base.Channel.ObtenerPersona(filtro);
        }
        
        public System.Threading.Tasks.Task<MinisterioDeportes.ReferenceMinisterioDeportesWCF.persona[]> ObtenerPersonaAsync(string filtro) {
            return base.Channel.ObtenerPersonaAsync(filtro);
        }
        
        public string AgregarRutina(MinisterioDeportes.ReferenceMinisterioDeportesWCF.rutina rutina) {
            return base.Channel.AgregarRutina(rutina);
        }
        
        public System.Threading.Tasks.Task<string> AgregarRutinaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.rutina rutina) {
            return base.Channel.AgregarRutinaAsync(rutina);
        }
        
        public string EliminarRutina(MinisterioDeportes.ReferenceMinisterioDeportesWCF.rutina rutina) {
            return base.Channel.EliminarRutina(rutina);
        }
        
        public System.Threading.Tasks.Task<string> EliminarRutinaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.rutina rutina) {
            return base.Channel.EliminarRutinaAsync(rutina);
        }
        
        public string EditarRutina(MinisterioDeportes.ReferenceMinisterioDeportesWCF.rutina rutina) {
            return base.Channel.EditarRutina(rutina);
        }
        
        public System.Threading.Tasks.Task<string> EditarRutinaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.rutina rutina) {
            return base.Channel.EditarRutinaAsync(rutina);
        }
        
        public MinisterioDeportes.ReferenceMinisterioDeportesWCF.rutina[] ObtenerRutina(string filtro) {
            return base.Channel.ObtenerRutina(filtro);
        }
        
        public System.Threading.Tasks.Task<MinisterioDeportes.ReferenceMinisterioDeportesWCF.rutina[]> ObtenerRutinaAsync(string filtro) {
            return base.Channel.ObtenerRutinaAsync(filtro);
        }
        
        public string AgregarPlanRutina(MinisterioDeportes.ReferenceMinisterioDeportesWCF.plan planRutina) {
            return base.Channel.AgregarPlanRutina(planRutina);
        }
        
        public System.Threading.Tasks.Task<string> AgregarPlanRutinaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.plan planRutina) {
            return base.Channel.AgregarPlanRutinaAsync(planRutina);
        }
        
        public string EliminarPlanRutina(MinisterioDeportes.ReferenceMinisterioDeportesWCF.plan planRutina) {
            return base.Channel.EliminarPlanRutina(planRutina);
        }
        
        public System.Threading.Tasks.Task<string> EliminarPlanRutinaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.plan planRutina) {
            return base.Channel.EliminarPlanRutinaAsync(planRutina);
        }
        
        public string EditarPlanRutina(MinisterioDeportes.ReferenceMinisterioDeportesWCF.plan planRutina) {
            return base.Channel.EditarPlanRutina(planRutina);
        }
        
        public System.Threading.Tasks.Task<string> EditarPlanRutinaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.plan planRutina) {
            return base.Channel.EditarPlanRutinaAsync(planRutina);
        }
        
        public MinisterioDeportes.ReferenceMinisterioDeportesWCF.plan[] ObtenerPlanRutina(string filtro) {
            return base.Channel.ObtenerPlanRutina(filtro);
        }
        
        public System.Threading.Tasks.Task<MinisterioDeportes.ReferenceMinisterioDeportesWCF.plan[]> ObtenerPlanRutinaAsync(string filtro) {
            return base.Channel.ObtenerPlanRutinaAsync(filtro);
        }
    }
}
