//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinisterioDeportes.ReferenceMinisterioDeportesWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonaDTO", Namespace="http://schemas.datacontract.org/2004/07/MinisterioDeportesWCF.Entidades")]
    [System.SerializableAttribute()]
    public partial class PersonaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellido1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellido2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isAdminField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cedula {
            get {
                return this.cedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.cedulaField, value) != true)) {
                    this.cedulaField = value;
                    this.RaisePropertyChanged("cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string apellido1 {
            get {
                return this.apellido1Field;
            }
            set {
                if ((object.ReferenceEquals(this.apellido1Field, value) != true)) {
                    this.apellido1Field = value;
                    this.RaisePropertyChanged("apellido1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string apellido2 {
            get {
                return this.apellido2Field;
            }
            set {
                if ((object.ReferenceEquals(this.apellido2Field, value) != true)) {
                    this.apellido2Field = value;
                    this.RaisePropertyChanged("apellido2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool isAdmin {
            get {
                return this.isAdminField;
            }
            set {
                if ((this.isAdminField.Equals(value) != true)) {
                    this.isAdminField = value;
                    this.RaisePropertyChanged("isAdmin");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeporteDTO", Namespace="http://schemas.datacontract.org/2004/07/MinisterioDeportesWCF.Entidades")]
    [System.SerializableAttribute()]
    public partial class DeporteDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RutinaDTO", Namespace="http://schemas.datacontract.org/2004/07/MinisterioDeportesWCF.Entidades")]
    [System.SerializableAttribute()]
    public partial class RutinaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string detallesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string detalles {
            get {
                return this.detallesField;
            }
            set {
                if ((object.ReferenceEquals(this.detallesField, value) != true)) {
                    this.detallesField = value;
                    this.RaisePropertyChanged("detalles");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlanDTO", Namespace="http://schemas.datacontract.org/2004/07/MinisterioDeportesWCF.Entidades")]
    [System.SerializableAttribute()]
    public partial class PlanDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string detallesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string detalles {
            get {
                return this.detallesField;
            }
            set {
                if ((object.ReferenceEquals(this.detallesField, value) != true)) {
                    this.detallesField = value;
                    this.RaisePropertyChanged("detalles");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReferenceMinisterioDeportesWCF.IWebServiceMD")]
    public interface IWebServiceMD {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/ValidarLogin", ReplyAction="http://tempuri.org/IWebServiceMD/ValidarLoginResponse")]
        MinisterioDeportes.ReferenceMinisterioDeportesWCF.PersonaDTO ValidarLogin(MinisterioDeportes.ReferenceMinisterioDeportesWCF.PersonaDTO usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/ValidarLogin", ReplyAction="http://tempuri.org/IWebServiceMD/ValidarLoginResponse")]
        System.Threading.Tasks.Task<MinisterioDeportes.ReferenceMinisterioDeportesWCF.PersonaDTO> ValidarLoginAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.PersonaDTO usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/AgregarDeporte", ReplyAction="http://tempuri.org/IWebServiceMD/AgregarDeporteResponse")]
        string AgregarDeporte(MinisterioDeportes.ReferenceMinisterioDeportesWCF.DeporteDTO deporte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/AgregarDeporte", ReplyAction="http://tempuri.org/IWebServiceMD/AgregarDeporteResponse")]
        System.Threading.Tasks.Task<string> AgregarDeporteAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.DeporteDTO deporte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/EliminarDeporte", ReplyAction="http://tempuri.org/IWebServiceMD/EliminarDeporteResponse")]
        string EliminarDeporte(MinisterioDeportes.ReferenceMinisterioDeportesWCF.DeporteDTO deporte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/EliminarDeporte", ReplyAction="http://tempuri.org/IWebServiceMD/EliminarDeporteResponse")]
        System.Threading.Tasks.Task<string> EliminarDeporteAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.DeporteDTO deporte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/EditarDeporte", ReplyAction="http://tempuri.org/IWebServiceMD/EditarDeporteResponse")]
        string EditarDeporte(MinisterioDeportes.ReferenceMinisterioDeportesWCF.DeporteDTO deporte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/EditarDeporte", ReplyAction="http://tempuri.org/IWebServiceMD/EditarDeporteResponse")]
        System.Threading.Tasks.Task<string> EditarDeporteAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.DeporteDTO deporte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/ObtenerDeportes", ReplyAction="http://tempuri.org/IWebServiceMD/ObtenerDeportesResponse")]
        MinisterioDeportes.ReferenceMinisterioDeportesWCF.DeporteDTO[] ObtenerDeportes(string filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/ObtenerDeportes", ReplyAction="http://tempuri.org/IWebServiceMD/ObtenerDeportesResponse")]
        System.Threading.Tasks.Task<MinisterioDeportes.ReferenceMinisterioDeportesWCF.DeporteDTO[]> ObtenerDeportesAsync(string filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/AgregarRutina", ReplyAction="http://tempuri.org/IWebServiceMD/AgregarRutinaResponse")]
        string AgregarRutina(MinisterioDeportes.ReferenceMinisterioDeportesWCF.RutinaDTO pRutina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/AgregarRutina", ReplyAction="http://tempuri.org/IWebServiceMD/AgregarRutinaResponse")]
        System.Threading.Tasks.Task<string> AgregarRutinaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.RutinaDTO pRutina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/ActualizarRutina", ReplyAction="http://tempuri.org/IWebServiceMD/ActualizarRutinaResponse")]
        string ActualizarRutina(MinisterioDeportes.ReferenceMinisterioDeportesWCF.RutinaDTO pRutina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/ActualizarRutina", ReplyAction="http://tempuri.org/IWebServiceMD/ActualizarRutinaResponse")]
        System.Threading.Tasks.Task<string> ActualizarRutinaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.RutinaDTO pRutina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/ObtenerRutinas", ReplyAction="http://tempuri.org/IWebServiceMD/ObtenerRutinasResponse")]
        MinisterioDeportes.ReferenceMinisterioDeportesWCF.RutinaDTO[] ObtenerRutinas(string filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/ObtenerRutinas", ReplyAction="http://tempuri.org/IWebServiceMD/ObtenerRutinasResponse")]
        System.Threading.Tasks.Task<MinisterioDeportes.ReferenceMinisterioDeportesWCF.RutinaDTO[]> ObtenerRutinasAsync(string filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/EliminarRutina", ReplyAction="http://tempuri.org/IWebServiceMD/EliminarRutinaResponse")]
        string EliminarRutina(MinisterioDeportes.ReferenceMinisterioDeportesWCF.RutinaDTO rutina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/EliminarRutina", ReplyAction="http://tempuri.org/IWebServiceMD/EliminarRutinaResponse")]
        System.Threading.Tasks.Task<string> EliminarRutinaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.RutinaDTO rutina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/AgregarPersona", ReplyAction="http://tempuri.org/IWebServiceMD/AgregarPersonaResponse")]
        string AgregarPersona(MinisterioDeportes.ReferenceMinisterioDeportesWCF.PersonaDTO persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/AgregarPersona", ReplyAction="http://tempuri.org/IWebServiceMD/AgregarPersonaResponse")]
        System.Threading.Tasks.Task<string> AgregarPersonaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.PersonaDTO persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/EliminarPersona", ReplyAction="http://tempuri.org/IWebServiceMD/EliminarPersonaResponse")]
        string EliminarPersona(MinisterioDeportes.ReferenceMinisterioDeportesWCF.PersonaDTO persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/EliminarPersona", ReplyAction="http://tempuri.org/IWebServiceMD/EliminarPersonaResponse")]
        System.Threading.Tasks.Task<string> EliminarPersonaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.PersonaDTO persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/ActualizarPersona", ReplyAction="http://tempuri.org/IWebServiceMD/ActualizarPersonaResponse")]
        string ActualizarPersona(MinisterioDeportes.ReferenceMinisterioDeportesWCF.PersonaDTO persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/ActualizarPersona", ReplyAction="http://tempuri.org/IWebServiceMD/ActualizarPersonaResponse")]
        System.Threading.Tasks.Task<string> ActualizarPersonaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.PersonaDTO persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/ObtenerParticipantes", ReplyAction="http://tempuri.org/IWebServiceMD/ObtenerParticipantesResponse")]
        MinisterioDeportes.ReferenceMinisterioDeportesWCF.PersonaDTO[] ObtenerParticipantes(string filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/ObtenerParticipantes", ReplyAction="http://tempuri.org/IWebServiceMD/ObtenerParticipantesResponse")]
        System.Threading.Tasks.Task<MinisterioDeportes.ReferenceMinisterioDeportesWCF.PersonaDTO[]> ObtenerParticipantesAsync(string filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/AgregarPlanRutina", ReplyAction="http://tempuri.org/IWebServiceMD/AgregarPlanRutinaResponse")]
        string AgregarPlanRutina(MinisterioDeportes.ReferenceMinisterioDeportesWCF.PlanDTO planRutina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/AgregarPlanRutina", ReplyAction="http://tempuri.org/IWebServiceMD/AgregarPlanRutinaResponse")]
        System.Threading.Tasks.Task<string> AgregarPlanRutinaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.PlanDTO planRutina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/EliminarPlanRutina", ReplyAction="http://tempuri.org/IWebServiceMD/EliminarPlanRutinaResponse")]
        string EliminarPlanRutina(MinisterioDeportes.ReferenceMinisterioDeportesWCF.PlanDTO planRutina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/EliminarPlanRutina", ReplyAction="http://tempuri.org/IWebServiceMD/EliminarPlanRutinaResponse")]
        System.Threading.Tasks.Task<string> EliminarPlanRutinaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.PlanDTO planRutina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/EditarPlanRutina", ReplyAction="http://tempuri.org/IWebServiceMD/EditarPlanRutinaResponse")]
        string EditarPlanRutina(MinisterioDeportes.ReferenceMinisterioDeportesWCF.PlanDTO planRutina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/EditarPlanRutina", ReplyAction="http://tempuri.org/IWebServiceMD/EditarPlanRutinaResponse")]
        System.Threading.Tasks.Task<string> EditarPlanRutinaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.PlanDTO planRutina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/ObtenerPlanes", ReplyAction="http://tempuri.org/IWebServiceMD/ObtenerPlanesResponse")]
        MinisterioDeportes.ReferenceMinisterioDeportesWCF.PlanDTO[] ObtenerPlanes(string filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceMD/ObtenerPlanes", ReplyAction="http://tempuri.org/IWebServiceMD/ObtenerPlanesResponse")]
        System.Threading.Tasks.Task<MinisterioDeportes.ReferenceMinisterioDeportesWCF.PlanDTO[]> ObtenerPlanesAsync(string filtro);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebServiceMDChannel : MinisterioDeportes.ReferenceMinisterioDeportesWCF.IWebServiceMD, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceMDClient : System.ServiceModel.ClientBase<MinisterioDeportes.ReferenceMinisterioDeportesWCF.IWebServiceMD>, MinisterioDeportes.ReferenceMinisterioDeportesWCF.IWebServiceMD {
        
        public WebServiceMDClient() {
        }
        
        public WebServiceMDClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceMDClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMDClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMDClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MinisterioDeportes.ReferenceMinisterioDeportesWCF.PersonaDTO ValidarLogin(MinisterioDeportes.ReferenceMinisterioDeportesWCF.PersonaDTO usuario) {
            return base.Channel.ValidarLogin(usuario);
        }
        
        public System.Threading.Tasks.Task<MinisterioDeportes.ReferenceMinisterioDeportesWCF.PersonaDTO> ValidarLoginAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.PersonaDTO usuario) {
            return base.Channel.ValidarLoginAsync(usuario);
        }
        
        public string AgregarDeporte(MinisterioDeportes.ReferenceMinisterioDeportesWCF.DeporteDTO deporte) {
            return base.Channel.AgregarDeporte(deporte);
        }
        
        public System.Threading.Tasks.Task<string> AgregarDeporteAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.DeporteDTO deporte) {
            return base.Channel.AgregarDeporteAsync(deporte);
        }
        
        public string EliminarDeporte(MinisterioDeportes.ReferenceMinisterioDeportesWCF.DeporteDTO deporte) {
            return base.Channel.EliminarDeporte(deporte);
        }
        
        public System.Threading.Tasks.Task<string> EliminarDeporteAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.DeporteDTO deporte) {
            return base.Channel.EliminarDeporteAsync(deporte);
        }
        
        public string EditarDeporte(MinisterioDeportes.ReferenceMinisterioDeportesWCF.DeporteDTO deporte) {
            return base.Channel.EditarDeporte(deporte);
        }
        
        public System.Threading.Tasks.Task<string> EditarDeporteAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.DeporteDTO deporte) {
            return base.Channel.EditarDeporteAsync(deporte);
        }
        
        public MinisterioDeportes.ReferenceMinisterioDeportesWCF.DeporteDTO[] ObtenerDeportes(string filtro) {
            return base.Channel.ObtenerDeportes(filtro);
        }
        
        public System.Threading.Tasks.Task<MinisterioDeportes.ReferenceMinisterioDeportesWCF.DeporteDTO[]> ObtenerDeportesAsync(string filtro) {
            return base.Channel.ObtenerDeportesAsync(filtro);
        }
        
        public string AgregarRutina(MinisterioDeportes.ReferenceMinisterioDeportesWCF.RutinaDTO pRutina) {
            return base.Channel.AgregarRutina(pRutina);
        }
        
        public System.Threading.Tasks.Task<string> AgregarRutinaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.RutinaDTO pRutina) {
            return base.Channel.AgregarRutinaAsync(pRutina);
        }
        
        public string ActualizarRutina(MinisterioDeportes.ReferenceMinisterioDeportesWCF.RutinaDTO pRutina) {
            return base.Channel.ActualizarRutina(pRutina);
        }
        
        public System.Threading.Tasks.Task<string> ActualizarRutinaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.RutinaDTO pRutina) {
            return base.Channel.ActualizarRutinaAsync(pRutina);
        }
        
        public MinisterioDeportes.ReferenceMinisterioDeportesWCF.RutinaDTO[] ObtenerRutinas(string filtro) {
            return base.Channel.ObtenerRutinas(filtro);
        }
        
        public System.Threading.Tasks.Task<MinisterioDeportes.ReferenceMinisterioDeportesWCF.RutinaDTO[]> ObtenerRutinasAsync(string filtro) {
            return base.Channel.ObtenerRutinasAsync(filtro);
        }
        
        public string EliminarRutina(MinisterioDeportes.ReferenceMinisterioDeportesWCF.RutinaDTO rutina) {
            return base.Channel.EliminarRutina(rutina);
        }
        
        public System.Threading.Tasks.Task<string> EliminarRutinaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.RutinaDTO rutina) {
            return base.Channel.EliminarRutinaAsync(rutina);
        }
        
        public string AgregarPersona(MinisterioDeportes.ReferenceMinisterioDeportesWCF.PersonaDTO persona) {
            return base.Channel.AgregarPersona(persona);
        }
        
        public System.Threading.Tasks.Task<string> AgregarPersonaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.PersonaDTO persona) {
            return base.Channel.AgregarPersonaAsync(persona);
        }
        
        public string EliminarPersona(MinisterioDeportes.ReferenceMinisterioDeportesWCF.PersonaDTO persona) {
            return base.Channel.EliminarPersona(persona);
        }
        
        public System.Threading.Tasks.Task<string> EliminarPersonaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.PersonaDTO persona) {
            return base.Channel.EliminarPersonaAsync(persona);
        }
        
        public string ActualizarPersona(MinisterioDeportes.ReferenceMinisterioDeportesWCF.PersonaDTO persona) {
            return base.Channel.ActualizarPersona(persona);
        }
        
        public System.Threading.Tasks.Task<string> ActualizarPersonaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.PersonaDTO persona) {
            return base.Channel.ActualizarPersonaAsync(persona);
        }
        
        public MinisterioDeportes.ReferenceMinisterioDeportesWCF.PersonaDTO[] ObtenerParticipantes(string filtro) {
            return base.Channel.ObtenerParticipantes(filtro);
        }
        
        public System.Threading.Tasks.Task<MinisterioDeportes.ReferenceMinisterioDeportesWCF.PersonaDTO[]> ObtenerParticipantesAsync(string filtro) {
            return base.Channel.ObtenerParticipantesAsync(filtro);
        }
        
        public string AgregarPlanRutina(MinisterioDeportes.ReferenceMinisterioDeportesWCF.PlanDTO planRutina) {
            return base.Channel.AgregarPlanRutina(planRutina);
        }
        
        public System.Threading.Tasks.Task<string> AgregarPlanRutinaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.PlanDTO planRutina) {
            return base.Channel.AgregarPlanRutinaAsync(planRutina);
        }
        
        public string EliminarPlanRutina(MinisterioDeportes.ReferenceMinisterioDeportesWCF.PlanDTO planRutina) {
            return base.Channel.EliminarPlanRutina(planRutina);
        }
        
        public System.Threading.Tasks.Task<string> EliminarPlanRutinaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.PlanDTO planRutina) {
            return base.Channel.EliminarPlanRutinaAsync(planRutina);
        }
        
        public string EditarPlanRutina(MinisterioDeportes.ReferenceMinisterioDeportesWCF.PlanDTO planRutina) {
            return base.Channel.EditarPlanRutina(planRutina);
        }
        
        public System.Threading.Tasks.Task<string> EditarPlanRutinaAsync(MinisterioDeportes.ReferenceMinisterioDeportesWCF.PlanDTO planRutina) {
            return base.Channel.EditarPlanRutinaAsync(planRutina);
        }
        
        public MinisterioDeportes.ReferenceMinisterioDeportesWCF.PlanDTO[] ObtenerPlanes(string filtro) {
            return base.Channel.ObtenerPlanes(filtro);
        }
        
        public System.Threading.Tasks.Task<MinisterioDeportes.ReferenceMinisterioDeportesWCF.PlanDTO[]> ObtenerPlanesAsync(string filtro) {
            return base.Channel.ObtenerPlanesAsync(filtro);
        }
    }
}
