//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinisterioDeportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class deporte
    {
        public deporte()
        {
            this.rutina = new HashSet<rutina>();
            this.persona = new HashSet<persona>();
        }
    
        public int ID { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<rutina> rutina { get; set; }
        public virtual ICollection<persona> persona { get; set; }
    }
}
