//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinisterioDeportes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db9ce858d6b9cb47658934a46901350226Entities3 : DbContext
    {
        public db9ce858d6b9cb47658934a46901350226Entities3()
            : base("name=db9ce858d6b9cb47658934a46901350226Entities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<deporte> deporte { get; set; }
        public virtual DbSet<persona> persona { get; set; }
        public virtual DbSet<plan_rutina> plan_rutina { get; set; }
        public virtual DbSet<rutina> rutina { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
