//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinisterioDeportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class persona
    {
        public persona()
        {
            this.deporte = new HashSet<deporte>();
        }
    
        public int cedula { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string apellido2 { get; set; }
    
        public virtual usuario usuario { get; set; }
        public virtual ICollection<deporte> deporte { get; set; }
    }
}
