//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinisterioDeportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class plan_rutina
    {
        public plan_rutina()
        {
            this.rutina1 = new HashSet<rutina>();
        }
    
        public int ID { get; set; }
        public int id_rutina { get; set; }
        public string descripcion { get; set; }
        public string detalles { get; set; }
    
        public virtual rutina rutina { get; set; }
        public virtual ICollection<rutina> rutina1 { get; set; }
    }
}
