//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinisterioDeportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class rutina
    {
        public rutina()
        {
            this.plan_rutina = new HashSet<plan_rutina>();
            this.plan_rutina1 = new HashSet<plan_rutina>();
        }
    
        public int ID { get; set; }
        public int id_deporte { get; set; }
        public string descripcion { get; set; }
        public string detalles { get; set; }
    
        public virtual deporte deporte { get; set; }
        public virtual ICollection<plan_rutina> plan_rutina { get; set; }
        public virtual ICollection<plan_rutina> plan_rutina1 { get; set; }
    }
}
