//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinisterioDeportesAccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class deporte
    {
        public deporte()
        {
            this.persona = new HashSet<persona>();
            this.plan = new HashSet<plan>();
        }
    
        public int ID { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<persona> persona { get; set; }
        public virtual ICollection<plan> plan { get; set; }
    }
}
