//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinisterioDeportesAccesoADatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MinisterioDeportesEntityDataModel : DbContext
    {
        public MinisterioDeportesEntityDataModel()
            : base("name=MinisterioDeportesEntityDataModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<deporte> deporte { get; set; }
        public virtual DbSet<persona> persona { get; set; }
        public virtual DbSet<plan> plan { get; set; }
        public virtual DbSet<rutina> rutina { get; set; }
    }
}
