//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinisterioDeportesAccesoADatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MinisterioDeportesEntityDataModel : DbContext
    {
        public MinisterioDeportesEntityDataModel()
            : base("name=MinisterioDeportesEntityDataModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<deporte> deporte { get; set; }
        public virtual DbSet<persona> persona { get; set; }
        public virtual DbSet<plan> plan { get; set; }
        public virtual DbSet<rutina> rutina { get; set; }
    }
}
