//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinisterioDeportesAccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class persona_deporte
    {
        public string persona { get; set; }
        public int deporte { get; set; }
        public Nullable<int> id_plan { get; set; }
    
        public virtual deporte deporte1 { get; set; }
        public virtual persona persona1 { get; set; }
        public virtual plan plan { get; set; }
    }
}
