//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinisterioDeportesAccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class persona_deporte
    {
        public string persona { get; set; }
        public int deporte { get; set; }
        public int id_plan { get; set; }
    
        public virtual deporte deporte1 { get; set; }
        public virtual persona persona1 { get; set; }
        public virtual plan plan { get; set; }
    }
}
