//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinisterioDeportesAccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class persona
    {
        public persona()
        {
            this.persona_deporte = new HashSet<persona_deporte>();
        }
    
        public string cedula { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string apellido2 { get; set; }
        public string password { get; set; }
        public bool is_admin { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<persona_deporte> persona_deporte { get; set; }
    }
}
