//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinisterioDeportesAccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class plan_rutina
    {
        public plan_rutina()
        {
            this.rutina1 = new HashSet<rutina>();
        }
    
        public int ID { get; set; }
        public int id_rutina { get; set; }
        public string descripcion { get; set; }
        public string detalles { get; set; }
    
        public virtual rutina rutina { get; set; }
        public virtual ICollection<rutina> rutina1 { get; set; }
    }
}
