//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinisterioDeportesAccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class plan
    {
        public plan()
        {
            this.deporte = new HashSet<deporte>();
            this.rutina = new HashSet<rutina>();
        }
    
        public int ID { get; set; }
        public string descripcion { get; set; }
        public string detalles { get; set; }
    
        public virtual ICollection<deporte> deporte { get; set; }
        public virtual ICollection<rutina> rutina { get; set; }
    }
}
