//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinisterioDeportesAccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class rutina
    {
        public rutina()
        {
            this.plan_rutina = new HashSet<plan_rutina>();
            this.plan_rutina1 = new HashSet<plan_rutina>();
        }
    
        public int ID { get; set; }
        public int id_deporte { get; set; }
        public string descripcion { get; set; }
        public string detalles { get; set; }
    
        public virtual deporte deporte { get; set; }
        public virtual ICollection<plan_rutina> plan_rutina { get; set; }
        public virtual ICollection<plan_rutina> plan_rutina1 { get; set; }
    }
}
